module.exports = {
    binance: {
        "bitcoin": ['BTCUSDT', 'BTCTUSD', 'BTCUSDC', 'BTCUSDS', 'BTCBUSD', 'BTCSTBUSD', 'BTCSTUSDT', 'BTCUSDP'],
        "ethereum": ['ETHUSDT', 'ETHTUSD', 'ETHUSDC', 'ETHBUSD', 'ETHUSDP'],
        "cardano": ["ADAUSDT"],
        "ripple": ['XRPUSDT', 'XRPTUSD', 'XRPUSDC', 'XRPBUSD'],
        "dogecoin": ['DOGEUSDT', 'DOGEUSDC', 'DOGEBUSD'],
        "algorand": [ 'ALGOUSDT', 'ALGOTUSD', 'ALGOUSDC', 'ALGOBUSD' ],
        "matic-network": [ 'MATICUSDT', 'MATICBUSD' ],
        "tron": [ 'TRXUSDT', 'TRXTUSD', 'TRXUSDC', 'TRXBUSD' ],
        "internet-computer": [ 'ICPBUSD', 'ICPUSDT' ],
        "binancecoin": ['BNBUSDT', 'BNBTUSD', 'BNBUSDC', 'BNBUSDS', 'BNBBUSD', 'BNBUSDP'],
        "solana": [ 'SOLUSDT', 'SOLBUSD' ],
        "polkadot": [ 'DOTBUSD', 'DOTUSDT' ],
        "avalanche-2": [ 'AVAXBUSD', 'AVAXUSDT' ],
        "terra-luna": [ 'LUNABUSD', 'LUNAUSDT' ],
        "uniswap": [ 'UNIBUSD', 'UNIUSDT' ],
        "chainlink": [ 'LINKUSDT', 'LINKTUSD', 'LINKUSDC', 'LINKBUSD' ],
        "litecoin": [ 'LTCUSDT', 'LTCTUSD', 'LTCUSDC', 'LTCBUSD' ],
        "cosmos": [ 'ATOMUSDT', 'ATOMUSDC', 'ATOMTUSD', 'ATOMBUSD' ],
        "filecoin": [ 'FILBUSD', 'FILUSDT' ],
        "stellar": [ 'XLMUSDT', 'XLMTUSD', 'XLMUSDC', 'XLMBUSD' ],
        "ftx-token": [ 'FTTUSDT', 'FTTBUSD' ],
        "theta-token": [ 'THETAUSDT', 'THETABUSD' ],
        "pancakeswap-token": [ 'CAKEBUSD', 'CAKEUSDT' ],
        "tezos": [ 'XTZUSDT', 'XTZBUSD' ],
        "aave": [ 'AAVEBUSD', 'AAVEUSDT' ],
    }
}